#!/usr/bin/env python
# -*- coding: UTF-8 -*-
#
# generated by wxGlade 0.8.2 on Thu Aug  9 10:26:51 2018
#

# This is an automatically generated file.
# Manual changes will be overwritten without warning!

import wx
import gettext
from MyFrame_old import MyFrame


class MyApp(wx.App):
    def OnInit(self):
        self.main_frame = MyFrame(None, wx.ID_ANY, "")
        self.SetTopWindow(self.main_frame)
        self.main_frame.Show()
        return True

# end of class MyApp

if __name__ == "__main__":
    gettext.install("app") # replace with the appropriate catalog name

    app = MyApp(0)
    app.MainLoop()
