#!/usr/bin/env python
# -*- coding: UTF-8 -*-
#
# generated by wxGlade 0.7.1 on Mon Jul  9 16:41:13 2018
#

import wx

# begin wxGlade: dependencies
import gettext
# end wxGlade

# begin wxGlade: extracode
# end wxGlade

import os

class MyDialog(wx.Dialog):
    def __init__(self, parent, id, title):
        # begin wxGlade: MyDialog.__init__
        wx.Dialog.__init__(self, parent, id, title)
        self.text_ctrl_1 = wx.TextCtrl(self, wx.ID_ANY, "text_ctrl_1")
        self.text_ctrl_2 = wx.TextCtrl(self, wx.ID_ANY, "text_ctrl_2")
        self.text_ctrl_3 = wx.TextCtrl(self, wx.ID_ANY, "text_ctrl_3")
        self.text_ctrl_4 = wx.TextCtrl(self, wx.ID_ANY, "text_ctrl_4")
        self.text_ctrl_5 = wx.TextCtrl(self, wx.ID_ANY, "text_ctrl_5")
        self.text_ctrl_6 = wx.TextCtrl(self, wx.ID_ANY, "text_ctrl_6")
        self.text_ctrl_7 = wx.TextCtrl(self, wx.ID_ANY, "text_ctrl_7")
        self.text_ctrl_8 = wx.TextCtrl(self, wx.ID_ANY, "text_ctrl_8")
        self.text_ctrl_9 = wx.TextCtrl(self, wx.ID_ANY, "text_ctrl_9", style=wx.TE_MULTILINE)
        self.text_ctrl_10 = wx.TextCtrl(self, wx.ID_ANY, "text_ctrl_10" 
                if parent.datasetID is None else parent.datasetName, style=wx.TE_READONLY)
#        self.text_ctrl_10 = wx.TextCtrl(self, wx.ID_ANY, "text_ctrl_10")
        self.button_1 = wx.Button(self, wx.ID_ANY, "Advanced Options")
        self.button_1.Bind(wx.EVT_BUTTON, self.OnButton_1)
        self.button_2 = wx.Button(self, wx.ID_OK, "Train")
        self.__set_properties()
        self.__do_layout()
        # end wxGlade

    def __set_properties(self):
        # begin wxGlade: MyDialog.__set_properties
        self.SetTitle("MyDialog")
        # end wxGlade

    def __do_layout(self):
        # begin wxGlade: MyDialog.__do_layout
        grid_sizer_1 = wx.GridBagSizer(0, 0)
        label_1 = wx.StaticText(self, wx.ID_ANY, "Traning epochs")
        grid_sizer_1.Add(label_1, (1, 1), (1, 10), 0, 0)
        grid_sizer_1.Add(self.text_ctrl_1, (2, 1), (1, 17), wx.EXPAND, 0)
        label_2 = wx.StaticText(self, wx.ID_ANY, "Snapshot interval (in epochs)")
        grid_sizer_1.Add(label_2, (4, 1), (1, 10), 0, 0)
        grid_sizer_1.Add(self.text_ctrl_2, (5, 1), (1, 17), wx.EXPAND, 0)
        label_3 = wx.StaticText(self, wx.ID_ANY, "Validation interval (in epochs)")
        grid_sizer_1.Add(label_3, (7, 1), (1, 10), 0, 0)
        grid_sizer_1.Add(self.text_ctrl_3, (8, 1), (1, 17), wx.EXPAND, 0)
        label_4 = wx.StaticText(self, wx.ID_ANY, "Random Seed")
        grid_sizer_1.Add(label_4, (10, 1), (1, 10), 0, 0)
        grid_sizer_1.Add(self.text_ctrl_4, (11, 1), (1, 17), wx.EXPAND, 0)
        label_5 = wx.StaticText(self, wx.ID_ANY, "Model Name")
        grid_sizer_1.Add(label_5, (13, 1), (1, 10), 0, 0)
        grid_sizer_1.Add(self.text_ctrl_5, (14, 1), (1, 17), wx.EXPAND, 0)
        label_6 = wx.StaticText(self, wx.ID_ANY, "Batch Size")
        grid_sizer_1.Add(label_6, (1, 20), (1, 10), 0, 0)
        grid_sizer_1.Add(self.text_ctrl_6, (2, 20), (1, 17), wx.EXPAND, 0)
        label_7 = wx.StaticText(self, wx.ID_ANY, "Solver type")
        grid_sizer_1.Add(label_7, (4, 20), (1, 10), 0, 0)
        grid_sizer_1.Add(self.text_ctrl_7, (5, 20), (1, 17), wx.EXPAND, 0)
        label_8 = wx.StaticText(self, wx.ID_ANY, "Base learning rate")
        grid_sizer_1.Add(label_8, (7, 20), (1, 10), 0, 0)
        grid_sizer_1.Add(self.text_ctrl_8, (8, 20), (1, 17), wx.EXPAND, 0)
        label_9 = wx.StaticText(self, wx.ID_ANY, "Select which GPU[s] you would like to use")
        grid_sizer_1.Add(label_9, (10, 20), (1, 10), 0, 0)
        grid_sizer_1.Add(self.text_ctrl_9, (11, 20), (1, 17), wx.EXPAND, 0)
        label_10 = wx.StaticText(self, wx.ID_ANY, "Dataset Name")
        grid_sizer_1.Add(label_10, (13, 20), (1, 10), 0, 0)
        grid_sizer_1.Add(self.text_ctrl_10, (14, 20), (1, 17), wx.EXPAND, 0)
        grid_sizer_1.Add(self.button_1, (16, 25), (1, 5), 0, 0)
        grid_sizer_1.Add(self.button_2, (16, 31), (1, 5), 0, 0)
        self.SetSizer(grid_sizer_1)
        grid_sizer_1.Fit(self)
        self.Layout()
        # end wxGlade
    
    def OnButton_1(self, event):
        pass

    def GetInfo(self):
        return [self.text_ctrl_1.GetLineText(0),
                self.text_ctrl_2.GetLineText(0),
                self.text_ctrl_3.GetLineText(0),
                self.text_ctrl_4.GetLineText(0),
                self.text_ctrl_5.GetLineText(0),
                self.text_ctrl_6.GetLineText(0),
                self.text_ctrl_7.GetLineText(0),
                self.text_ctrl_8.GetLineText(0),
                self.text_ctrl_9.GetLineText(0),
                self.text_ctrl_10.GetLineText(0)] 

# end of class MyDialog

class MyApp(wx.App):
    def OnInit(self):
        dialog = MyDialog(None, wx.ID_ANY, "")
        dialog.Show()
        return True


if __name__ == "__main__":
    app = MyApp(0)
    app.MainLoop()
