# -*- coding: UTF-8 -*-
#
# generated by wxGlade 0.8.2 on Tue Aug 21 13:46:28 2018
#

import wx
import wx.aui
import os
# begin wxGlade: dependencies
# end wxGlade

# begin wxGlade: extracode
# end wxGlade
from mynotebook import MyNotebook


os.environ["UBUNTU_MENUPROXY"] = "0"

class MyFrame(wx.Frame):
    def __init__(self, *args, **kwds):
        # begin wxGlade: MyFrame.__init__
        kwds["style"] = kwds.get("style", 0) | wx.DEFAULT_FRAME_STYLE
        wx.Frame.__init__(self, *args, **kwds)
        self.SetSize((1194, 922))
        
        # Menu Bar
        self.frame_menubar = wx.MenuBar()
        wxglade_tmp_menu = wx.Menu()
        wxglade_tmp_menu.Append(wx.ID_ANY, _("Import"), "")
        wxglade_tmp_menu.Append(wx.ID_ANY, _("Export"), "")
        self.frame_menubar.Append(wxglade_tmp_menu, _("File"))
        wxglade_tmp_menu = wx.Menu()
        wxglade_tmp_menu.Append(wx.ID_ANY, _("Create"), "")
        wxglade_tmp_menu.Append(wx.ID_ANY, _("Load"), "")
        self.frame_menubar.Append(wxglade_tmp_menu, _("Datasets"))
        wxglade_tmp_menu = wx.Menu()
        wxglade_tmp_menu.Append(wx.ID_ANY, _("Test single"), "")
        wxglade_tmp_menu.Append(wx.ID_ANY, _("Test a folder"), "")
        self.frame_menubar.Append(wxglade_tmp_menu, _("Models"))
        self.SetMenuBar(self.frame_menubar)
        # Menu Bar end
        
        # Tool Bar
        self.tool_bar = wx.ToolBar(self, wx.ID_ANY)
        self.SetToolBar(self.tool_bar)
        self.tool_new = self.tool_bar.AddTool(1, _("New"), wx.Bitmap("./icons/add.png", wx.BITMAP_TYPE_ANY), wx.NullBitmap, wx.ITEM_NORMAL, _("Add"), "")
        self.tool_load = self.tool_bar.AddTool(2, _("Load"), wx.Bitmap("./icons/upload.png", wx.BITMAP_TYPE_ANY), wx.NullBitmap, wx.ITEM_NORMAL, _("Load"), "")
        self.tool_save = self.tool_bar.AddTool(3, _("Save"), wx.Bitmap("./icons/diskette(1).png", wx.BITMAP_TYPE_ANY), wx.NullBitmap, wx.ITEM_NORMAL, _("Save"), "")
        self.tool_bar.AddSeparator()
        self.tool_train_spec = self.tool_bar.AddTool(4, _("Make a pretrained model"), wx.Bitmap("./icons/3d-modeling.png", wx.BITMAP_TYPE_ANY), wx.NullBitmap, wx.ITEM_NORMAL, _("Make a model"), "")
        self.tool_train_start = self.tool_bar.AddTool(5, _("Train"), wx.Bitmap("./icons/play(1).png", wx.BITMAP_TYPE_ANY), wx.NullBitmap, wx.ITEM_NORMAL, _("Train"), "")
        self.tool_bar.AddSeparator()
        self.tool_test = self.tool_bar.AddTool(6, _("Classify one"), wx.Bitmap("./icons/background.png", wx.BITMAP_TYPE_ANY), wx.NullBitmap, wx.ITEM_NORMAL, _("Classify one"), "")
        self.tool_bar.AddTool(wx.ID_ANY, _("Classify many"), wx.Bitmap("./icons/image.png", wx.BITMAP_TYPE_ANY), wx.NullBitmap, wx.ITEM_NORMAL, _("Classify many"), "")
        # Tool Bar end

        # TreeCtrl
        self.tree_ctrl_1 = wx.TreeCtrl(self, wx.ID_ANY)#, style=wx.BORDER_SUNKEN | wx.TR_HAS_BUTTONS)
        self.tree_ctrl_2 = wx.TreeCtrl(self, wx.ID_ANY)#, style=wx.BORDER_SUNKEN | wx.TR_HAS_BUTTONS)
        # TreeCtrl end

        # AuiNotebook
        self.notebook_1 = MyNotebook(self, wx.ID_ANY)
        # AuiNotebook end

        # log window
        self.text_ctrl_1 = wx.TextCtrl(self, wx.ID_ANY, "log\n", style=wx.HSCROLL | wx.TE_LEFT | wx.TE_MULTILINE | wx.TE_READONLY)
        # log window end

        self.__set_properties()
        self.__do_layout()
        # end wxGlade


    def __set_properties(self):
        # begin wxGlade: MyFrame.__set_properties
        self.SetTitle(_("Tensorflow GUI"))
        self.tool_bar.Realize()
        self.text_ctrl_1.SetBackgroundColour(wx.Colour(235, 235, 235))
        # end wxGlade

    def __do_layout(self):
        # begin wxGlade: MyFrame.__do_layout
        sizer_1 = wx.BoxSizer(wx.VERTICAL)
        sizer_2 = wx.BoxSizer(wx.HORIZONTAL)
        sizer_3 = wx.BoxSizer(wx.VERTICAL)
        sizer_3.Add(self.tree_ctrl_1, 1, wx.EXPAND | wx.BOTTOM, 5)
        sizer_3.Add(self.tree_ctrl_2, 1, wx.EXPAND | wx.TOP, 5)
        sizer_2.Add(sizer_3, 2, wx.EXPAND, 0)
        sizer_2.Add(self.notebook_1, 5, wx.EXPAND, 0)
        sizer_1.Add(sizer_2, 4, wx.EXPAND, 0)
        sizer_1.Add(self.text_ctrl_1, 2, wx.ALL | wx.EXPAND, 0)
        self.SetSizer(sizer_1)
        self.Layout()
        # end wxGlade

    def createTrainSpecPanel(self, parent, dict):
        self.notebook_1.panel_3_count += 1
        train_spec_count = self.notebook_1.panel_3_count
#        for i in range(len(self.notebook_1.panel_3_list)):
#            self.notebook_1.AddPage(self.notebook_1.panel_3_list[i], _("Train Spec"))
        train_spec_panel = wx.Panel(self.notebook_1, wx.ID_ANY)
        text_ctrl_14 = wx.TextCtrl(train_spec_panel, wx.ID_ANY, "14")
        text_ctrl_19 = wx.TextCtrl(train_spec_panel, wx.ID_ANY, str(dict['validation interval']) if 'validation interval' in dict else "19")
        text_ctrl_15 = wx.TextCtrl(train_spec_panel, wx.ID_ANY, "15")
        text_ctrl_20 = wx.TextCtrl(train_spec_panel, wx.ID_ANY, dict['optimizer'] if 'optimizer' in dict else "20")
        text_ctrl_16 = wx.TextCtrl(train_spec_panel, wx.ID_ANY, str(dict['max_iter']) if 'max_iter' in dict else "26")
        text_ctrl_21 = wx.TextCtrl(train_spec_panel, wx.ID_ANY, str(dict['lr']) if 'lr' in dict else "21")
        text_ctrl_17 = wx.TextCtrl(train_spec_panel, wx.ID_ANY, "17")
        text_ctrl_22 = wx.TextCtrl(train_spec_panel, wx.ID_ANY, str(dict['seed']) if 'seed' in dict else "22")
        text_ctrl_18 = wx.TextCtrl(train_spec_panel, wx.ID_ANY, str(dict['batch_size']) if 'batch_size' in dict else "18")
        text_ctrl_23 = wx.TextCtrl(train_spec_panel, wx.ID_ANY, "23")

        grid_sizer_3 = wx.GridBagSizer(0, 0)
        label_14 = wx.StaticText(train_spec_panel, wx.ID_ANY, _("Model select"))
        label_14.SetFont(wx.Font(13, wx.DEFAULT, wx.NORMAL, wx.NORMAL, 0, "Ubuntu"))
        grid_sizer_3.Add(label_14, (1, 1), (1, 10), 0, 0)
        label_19 = wx.StaticText(train_spec_panel, wx.ID_ANY, _("Sanpshot interval(in epochs)"))
        label_19.SetFont(wx.Font(13, wx.DEFAULT, wx.NORMAL, wx.NORMAL, 0, "Ubuntu"))
        grid_sizer_3.Add(label_19, (1, 21), (1, 10), 0, 0)
        grid_sizer_3.Add(text_ctrl_14, (2, 1), (1, 18), wx.EXPAND, 0)
        grid_sizer_3.Add(text_ctrl_19, (2, 21), (1, 18), wx.EXPAND | wx.RIGHT, 30)
        label_15 = wx.StaticText(train_spec_panel, wx.ID_ANY, _("Checkpoint name"))
        label_15.SetFont(wx.Font(13, wx.DEFAULT, wx.NORMAL, wx.NORMAL, 0, "Ubuntu"))
        grid_sizer_3.Add(label_15, (4, 1), (1, 10), 0, 0)
        label_20 = wx.StaticText(train_spec_panel, wx.ID_ANY, _("Solver type"))
        label_20.SetFont(wx.Font(13, wx.DEFAULT, wx.NORMAL, wx.NORMAL, 0, "Ubuntu"))
        grid_sizer_3.Add(label_20, (4, 21), (1, 10), 0, 0)
        grid_sizer_3.Add(text_ctrl_15, (5, 1), (1, 18), wx.EXPAND, 0)
        grid_sizer_3.Add(text_ctrl_20, (5, 21), (1, 18), wx.EXPAND | wx.RIGHT, 30)
        label_16 = wx.StaticText(train_spec_panel, wx.ID_ANY, _("Training epochs"))
        label_16.SetFont(wx.Font(13, wx.DEFAULT, wx.NORMAL, wx.NORMAL, 0, "Ubuntu"))
        grid_sizer_3.Add(label_16, (7, 1), (1, 10), 0, 0)
        label_21 = wx.StaticText(train_spec_panel, wx.ID_ANY, _("Base Learning rate"))
        label_21.SetFont(wx.Font(13, wx.DEFAULT, wx.NORMAL, wx.NORMAL, 0, "Ubuntu"))
        grid_sizer_3.Add(label_21, (7, 21), (1, 10), 0, 0)
        grid_sizer_3.Add(text_ctrl_16, (8, 1), (1, 18), wx.EXPAND, 0)
        grid_sizer_3.Add(text_ctrl_21, (8, 21), (1, 18), wx.EXPAND | wx.RIGHT, 30)
        label_17 = wx.StaticText(train_spec_panel, wx.ID_ANY, _("Dataset name"))
        label_17.SetFont(wx.Font(13, wx.DEFAULT, wx.NORMAL, wx.NORMAL, 0, "Ubuntu"))
        grid_sizer_3.Add(label_17, (10, 1), (1, 10), 0, 0)
        label_22 = wx.StaticText(train_spec_panel, wx.ID_ANY, _("Random seed"))
        label_22.SetFont(wx.Font(13, wx.DEFAULT, wx.NORMAL, wx.NORMAL, 0, "Ubuntu"))
        grid_sizer_3.Add(label_22, (10, 21), (1, 10), 0, 0)
        grid_sizer_3.Add(text_ctrl_17, (11, 1), (1, 18), wx.EXPAND, 0)
        grid_sizer_3.Add(text_ctrl_22, (11, 21), (1, 18), wx.EXPAND | wx.RIGHT, 30)
        label_18 = wx.StaticText(train_spec_panel, wx.ID_ANY, _("Batch size"))
        label_18.SetFont(wx.Font(13, wx.DEFAULT, wx.NORMAL, wx.NORMAL, 0, "Ubuntu"))
        grid_sizer_3.Add(label_18, (13, 1), (1, 10), 0, 0)
        label_23 = wx.StaticText(train_spec_panel, wx.ID_ANY, _("Select which GPU[s] you would like to use"))
        label_23.SetFont(wx.Font(13, wx.DEFAULT, wx.NORMAL, wx.NORMAL, 0, "Ubuntu"))
        grid_sizer_3.Add(label_23, (13, 21), (1, 10), 0, 0)
        grid_sizer_3.Add(text_ctrl_18, (14, 1), (1, 18), wx.EXPAND, 0)
        grid_sizer_3.Add(text_ctrl_23, (14, 21), (1, 18), wx.EXPAND | wx.RIGHT, 30)
        train_spec_panel.SetSizer(grid_sizer_3)
#        grid_sizer_3.AddGrowableRow(18)
#        grid_sizer_3.AddGrowableCol(1)
#        grid_sizer_3.AddGrowableCol(21)
        self.notebook_1.panel_3_list.append(train_spec_panel)
        self.notebook_1.AddPage(self.notebook_1.panel_3_list[-1], _("Train Spec %d"%train_spec_count), select=True)
        return train_spec_panel

    def createModelSpecPanel(self, parent, dict):
        self.notebook_1.panel_2_count += 1
        model_spec_count = self.notebook_1.panel_2_count
#        for i in range(len(self.notebook_1.panel_2_list)):
#            self.notebook_1.AddPage(self.notebook_1.panel_2_list[i], _("Model Spec"))
        model_spec_panel = wx.Panel(parent, wx.ID_ANY)
        text_ctrl_9 = wx.TextCtrl(model_spec_panel, wx.ID_ANY, dict['type'] if 'type' in dict else "9")
        text_ctrl_10 = wx.TextCtrl(model_spec_panel, wx.ID_ANY, dict['n_layer'] if 'n_layer' in dict else "10")
        text_ctrl_11 = wx.TextCtrl(model_spec_panel, wx.ID_ANY, dict['input_size'] if 'image_size' in dict else "11")
        text_ctrl_13 = wx.TextCtrl(model_spec_panel, wx.ID_ANY, "13")
        text_ctrl_12 = wx.TextCtrl(model_spec_panel, wx.ID_ANY, dict['output_size'] if 'output_size' in dict else "12")

        grid_sizer_2 = wx.GridBagSizer(5, 5)
        label_9 = wx.StaticText(model_spec_panel, wx.ID_ANY, _("Network Type"), style=wx.ALIGN_LEFT)
        label_9.SetFont(wx.Font(13, wx.DEFAULT, wx.NORMAL, wx.NORMAL, 0, "Ubuntu"))
        grid_sizer_2.Add(label_9, (1, 1), (1, 6), wx.ALIGN_CENTER_VERTICAL, 0)
        grid_sizer_2.Add(text_ctrl_9, (1, 8), (1, 27), wx.EXPAND | wx.RIGHT, 20)
        label_10 = wx.StaticText(model_spec_panel, wx.ID_ANY, _("Number of Layers"), style=wx.ALIGN_LEFT)
        label_10.SetFont(wx.Font(13, wx.DEFAULT, wx.NORMAL, wx.NORMAL, 0, "Ubuntu"))
        grid_sizer_2.Add(label_10, (2, 1), (1, 6), wx.ALIGN_CENTER_VERTICAL, 0)
        grid_sizer_2.Add(text_ctrl_10, (2, 8), (1, 27), wx.EXPAND | wx.RIGHT, 20)
        label_11 = wx.StaticText(model_spec_panel, wx.ID_ANY, _("Image Size (Input)"), style=wx.ALIGN_LEFT)
        label_11.SetFont(wx.Font(13, wx.DEFAULT, wx.NORMAL, wx.NORMAL, 0, "Ubuntu"))
        grid_sizer_2.Add(label_11, (3, 1), (1, 6), wx.ALIGN_CENTER_VERTICAL, 0)
        grid_sizer_2.Add(text_ctrl_11, (3, 8), (1, 13), wx.EXPAND, 0)
        label_13 = wx.StaticText(model_spec_panel, wx.ID_ANY, _("X"), style=wx.ALIGN_CENTER)
        grid_sizer_2.Add(label_13, (3, 21), (1, 1), wx.ALIGN_CENTER, 0)
        grid_sizer_2.Add(text_ctrl_13, (3, 22), (1, 13), wx.EXPAND | wx.RIGHT, 20)
        label_12 = wx.StaticText(model_spec_panel, wx.ID_ANY, _("Number of Classes / Demension (Output)"))
        label_12.SetFont(wx.Font(13, wx.DEFAULT, wx.NORMAL, wx.NORMAL, 0, "Ubuntu"))
        grid_sizer_2.Add(label_12, (4, 1), (1, 6), wx.ALIGN_CENTER_VERTICAL, 0)
        grid_sizer_2.Add(text_ctrl_12, (4, 8), (1, 27), wx.EXPAND | wx.RIGHT, 20)
        model_spec_panel.SetSizer(grid_sizer_2)
#        grid_sizer_2.AddGrowableRow(18)
#        grid_sizer_2.AddGrowableCol(8)
#        grid_sizer_2.AddGrowableCol(22)
        self.notebook_1.panel_2_list.append(model_spec_panel)
        self.notebook_1.AddPage(self.notebook_1.panel_2_list[-1], _("Model Spec %d"%model_spec_count), select=True)
        return model_spec_panel

    def createDataSpecPanel(self, parent, dict):
        self.notebook_1.panel_1_count += 1
        data_spec_count = self.notebook_1.panel_1_count
        data_spec_panel = wx.Panel(parent, wx.ID_ANY)
        text_ctrl_2 = wx.TextCtrl(data_spec_panel, wx.ID_ANY, dict['path'] if 'path' in dict else "2", style=wx.TE_READONLY)
        text_ctrl_3 = wx.TextCtrl(data_spec_panel, wx.ID_ANY, "3", style=wx.TE_READONLY)
        text_ctrl_4 = wx.TextCtrl(data_spec_panel, wx.ID_ANY, "4", style=wx.TE_READONLY)
        text_ctrl_5 = wx.TextCtrl(data_spec_panel, wx.ID_ANY, "5", style=wx.TE_READONLY)
        text_ctrl_6 = wx.TextCtrl(data_spec_panel, wx.ID_ANY, "6", style=wx.TE_READONLY)
        combo_box_1 = wx.ComboBox(data_spec_panel, wx.ID_ANY, choices=["combo_box_1"], style=wx.CB_DROPDOWN)
        text_ctrl_8 = wx.TextCtrl(data_spec_panel, wx.ID_ANY, "8")
        text_ctrl_7 = wx.TextCtrl(data_spec_panel, wx.ID_ANY, "7")

        grid_sizer_1 = wx.GridBagSizer(5, 5)
        label_1 = wx.StaticText(data_spec_panel, wx.ID_ANY, _("Dataset Path"), style=wx.ALIGN_LEFT)
        label_1.SetFont(wx.Font(13, wx.DEFAULT, wx.NORMAL, wx.NORMAL, 0, "Ubuntu"))
        grid_sizer_1.Add(label_1, (1, 1), (1, 6), wx.ALIGN_CENTER_VERTICAL, 0)
        grid_sizer_1.Add(text_ctrl_2, (1, 8), (1, 27), wx.EXPAND | wx.RIGHT, 20)
        label_2 = wx.StaticText(data_spec_panel, wx.ID_ANY, _("Number of Classes"), style=wx.ALIGN_LEFT)
        label_2.SetFont(wx.Font(13, wx.DEFAULT, wx.NORMAL, wx.NORMAL, 0, "Ubuntu"))
        grid_sizer_1.Add(label_2, (2, 1), (1, 6), wx.ALIGN_CENTER_VERTICAL, 0)
        grid_sizer_1.Add(text_ctrl_3, (2, 8), (1, 27), wx.EXPAND | wx.RIGHT, 20)
        label_3 = wx.StaticText(data_spec_panel, wx.ID_ANY, _("Number of Images"), style=wx.ALIGN_CENTER | wx.ALIGN_LEFT)
        label_3.SetFont(wx.Font(13, wx.DEFAULT, wx.NORMAL, wx.NORMAL, 0, "Ubuntu"))
        grid_sizer_1.Add(label_3, (3, 1), (1, 6), wx.ALIGN_CENTER_VERTICAL, 0)
        grid_sizer_1.Add(text_ctrl_4, (3, 8), (1, 27), wx.EXPAND | wx.RIGHT, 20)
        label_4 = wx.StaticText(data_spec_panel, wx.ID_ANY, _("Image Size"), style=wx.ALIGN_CENTER | wx.ALIGN_LEFT)
        label_4.SetFont(wx.Font(13, wx.DEFAULT, wx.NORMAL, wx.NORMAL, 0, "Ubuntu"))
        grid_sizer_1.Add(label_4, (4, 1), (1, 6), wx.ALIGN_CENTER_VERTICAL, 0)
        grid_sizer_1.Add(text_ctrl_5, (4, 8), (1, 13), wx.EXPAND | wx.RIGHT, 0)
        label_7 = wx.StaticText(data_spec_panel, wx.ID_ANY, _("X"))
        grid_sizer_1.Add(label_7, (4, 21), (1, 1), wx.ALIGN_CENTER, 0)
        grid_sizer_1.Add(text_ctrl_6, (4, 22), (1, 13), wx.EXPAND | wx.RIGHT, 20)
        label_5 = wx.StaticText(data_spec_panel, wx.ID_ANY, _("Image Type"), style=wx.ALIGN_CENTER | wx.ALIGN_LEFT)
        label_5.SetFont(wx.Font(13, wx.DEFAULT, wx.NORMAL, wx.NORMAL, 0, "Ubuntu"))
        grid_sizer_1.Add(label_5, (5, 1), (1, 6), wx.ALIGN_CENTER_VERTICAL, 0)
        grid_sizer_1.Add(combo_box_1, (5, 8), (1, 27), wx.EXPAND | wx.RIGHT, 20)
        label_6 = wx.StaticText(data_spec_panel, wx.ID_ANY, _("% of Testing"), style=wx.ALIGN_CENTER | wx.ALIGN_LEFT)
        label_6.SetFont(wx.Font(13, wx.DEFAULT, wx.NORMAL, wx.NORMAL, 0, "Ubuntu"))
        grid_sizer_1.Add(label_6, (6, 1), (1, 6), wx.ALIGN_CENTER_VERTICAL, 0)
        grid_sizer_1.Add(text_ctrl_8, (6, 8), (1, 27), wx.EXPAND | wx.RIGHT, 20)
        label_8 = wx.StaticText(data_spec_panel, wx.ID_ANY, _("Maximum Samples per Class"), style=wx.ALIGN_LEFT)
        label_8.SetFont(wx.Font(13, wx.DEFAULT, wx.NORMAL, wx.NORMAL, 0, "Ubuntu"))
        grid_sizer_1.Add(label_8, (7, 1), (1, 6), wx.ALIGN_CENTER_VERTICAL, 0)
        grid_sizer_1.Add(text_ctrl_7, (7, 8), (1, 27), wx.EXPAND | wx.RIGHT, 20)
        data_spec_panel.SetSizer(grid_sizer_1)
#        grid_sizer_1.AddGrowableRow(18)
        #grid_sizer_1.AddGrowableCol(8)
        #grid_sizer_1.AddGrowableCol(22)
        self.notebook_1.panel_1_list.append(data_spec_panel)
        self.notebook_1.AddPage(self.notebook_1.panel_1_list[-1], _("Data Spec %d"%data_spec_count), True)
        #return self.notebook_1.GetPage(self.notebook_1.GetPageCount()-1)
        #return self.notebook_1.GetPage(0)
        return data_spec_panel

# end of class MyFrame
